#' Plot heatmap
#'
#' Plot a phenotype x phenotype correlation matrix based on genetic overlap.
#' @param top_targets \link[data.table]{data.table} of prioritised targets
#' generated by \link[MultiEWCE]{prioritise_targets}.
#' @param row_side_vars Variables to include in row-side
#' metadata annotations.
#' @param col_side_vars Variables to include in column-side
#' metadata annotations.
#' @param fontsize Axis labels font size.
#' @param show_plot Print the plot after generating it.
#' @param save_plot Path to save plot to.
#' @param seed Set the seed for reproducible clustering.
#' @param interact Make the plot interactive via \link[heatmaply]{heatmaply}.
#'
#' @inheritParams HPOExplorer::make_phenos_dataframe
#' @inheritParams ComplexHeatmap::Heatmap
#' @inheritParams grDevices::pdf
#' @returns Plot
#'
#' @export
#' @importFrom HPOExplorer load_phenotype_to_genes add_gene_frequency
#' @importFrom HPOExplorer add_ancestor add_ont_lvl add_onset
#' @importFrom data.table := dcast.data.table setnafill
#' @importFrom stats cor
#' @examples
#' top_targets <- example_targets$top_targets
#' hm <- correlation_heatmap(top_targets = top_targets)
correlation_heatmap <- function(top_targets,
                                row_side_vars = c("ancestor_name",
                                                  "ontLvl",
                                                  "Onset_top"),
                                col_side_vars = c("n_celltypes",
                                                  "n_genes"),
                                phenotype_to_genes=
                                  HPOExplorer::load_phenotype_to_genes(),
                                col = pals::gnuplot(),
                                show_plot = TRUE,
                                save_plot = tempfile(
                                  fileext = "correlation_heatmap.pdf"),
                                height = 10,
                                width = height*1.3,
                                fontsize = 7,
                                row_km = 3,
                                column_km = row_km,
                                row_km_repeats = 1000,
                                column_km_repeats = row_km_repeats,
                                seed = 2023,
                                interact = FALSE,
                                verbose = TRUE
                    ){
  # templateR:::args2vars(correlation_heatmap)
  requireNamespace("pals")

  if(!is.null(seed)) set.seed(seed)
  #### Create matrix ####
  X_cor <- hpo_to_matrix(terms = unique(top_targets$HPO_ID),
                         phenotype_to_genes = phenotype_to_genes,
                         run_cor = TRUE,
                         verbose = verbose)
  #### Create row/col annotations ####
  annot <- agg_results(phenos = top_targets,
                       group_var = c("Phenotype",row_side_vars),
                       count_var = "CellType",
                       verbose = verbose)
  #### Heatmaply version ####
  if(isTRUE(interact)){
    requireNamespace("heatmaply")
    X_cor[is.na(X_cor)] <- 0
    hm <- heatmaply::heatmaply(X_cor,
                               row_side_colors=annot[,row_side_vars,with=FALSE],
                               k_row = row_km,
                               k_col = column_km,
                               colors = col)
    #### Plotly version ####
    # plotly::plot_ly() |>
    #   plotly::add_heatmap(x=colnames(X_cor),
    #                       y=rownames(X_cor),
    #                       z=X_cor)
  #### ComplexHeatmap version ####
  } else {
    requireNamespace("ComplexHeatmap")
    requireNamespace("grid")
    requireNamespace("grDevices")

    ra <- make_rannot(annot = annot,
                      row_side_vars = row_side_vars)

    ca <- make_cannot(annot = annot,
                      col_side_vars = col_side_vars)
    hm <- ComplexHeatmap::Heatmap(matrix = X_cor,
                                  name = "Genetic correlation",
                                  col = col,
                                  right_annotation = ra,
                                  top_annotation = ca,
                                  row_dend_side = "left",
                                  column_names_gp =
                                    grid::gpar(fontsize = fontsize),
                                  row_names_gp =
                                    grid::gpar(fontsize = fontsize),
                                  row_km = row_km,
                                  column_km = column_km,
                                  row_km_repeats = row_km_repeats,
                                  column_km_repeats = column_km_repeats,
                                  gap = grid::unit(.5, "mm"),
                                  row_gap = grid::unit(0, "mm"),
                                  column_gap = grid::unit(0, "mm"),
                                  cluster_rows = TRUE,
                                  cluster_columns = TRUE,
                                  cluster_row_slices = FALSE,
                                  cluster_column_slices = FALSE,
                                  row_dend_reorder = FALSE,
                                  column_dend_reorder = FALSE)
    # ComplexHeatmap::row_order(hm)
    #### Save plot ####
    if(!is.null(save_plot)){
      requireNamespace("grDevices")
      if(endsWith(save_plot,".pdf")){
        {
          grDevices::pdf(file = save_plot,
                         width = width,
                         height = height)
          methods::show(hm)
          grDevices::dev.off()
        }
      } else if(endsWith(save_plot,".png")){
        {
          grDevices::png(file = save_plot,
                         width = width,
                         height = height)
          methods::show(hm)
          grDevices::dev.off()
        }
      }
    }
  }
  #### Show plot ####
  if(isTRUE(show_plot)) methods::show(hm)
  #### Return ####
  return(hm)
}
