#' Create interactive network plot start to finish
#'
#' This puts all the functions together from getting the subset of results
#'  to creating the final interactive plot.
#'
#' @param results The cell type-phenotype enrichment results generated by
#'  \link[MultiEWCE]{gen_results}
#'  and merged together with \link[MultiEWCE]{merge_results}.
#' @param cell_type The cell type of interest to be plotted.
#' @param q_threshold The q value threshold to subset the \code{results} by.
#' @param fold_threshold The minimum fold change in specific expression
#'  to subset the \code{results} by.
#' @inheritParams HPOExplorer::make_phenos_dataframe
#' @inheritParams HPOExplorer::ggnetwork_plot
#' @returns A named list of outputs,
#'  including a interactive network plot of the selected subset
#' of results from RD EWCE analysis.
#'
#' @export
#' @importFrom HPOExplorer get_hpo load_phenotype_to_genes adjacency_matrix
#' @importFrom HPOExplorer make_hoverboxes make_network_object ggnetwork_plot
#' @examples
#' res_list <- ggnetwork_plot_full(cell_type = "Microglia")
ggnetwork_plot_full <- function(cell_type,
                                results = load_example_results(),
                                hpo = HPOExplorer::get_hpo(),
                                phenotype_to_genes =
                                  HPOExplorer::load_phenotype_to_genes(),
                                q_threshold = 0.0005,
                                fold_threshold = 1,
                                columns = list(
                                  Phenotype="Phenotype",
                                  ID="HPO_ID",
                                  ontLvl_genes="ontLvl_geneCount_ratio",
                                  Description="description",
                                  CellType="CellType",
                                  p="p",
                                  q="q",
                                  fold_change="fold_change"),
                                colour_var = "fold_change",
                                interactive = TRUE,
                                verbose = TRUE){
  # templateR:::source_all()
  # templateR:::args2vars(ggnetwork_plot_full)

  messager("ggnetwork_plot_full",v=verbose)
  phenos <- subset_phenos(phenotype_to_genes = phenotype_to_genes,
                          results = results,
                          hpo = hpo,
                          cell_type = cell_type,
                          q_threshold = q_threshold,
                          fold_threshold = fold_threshold,
                          verbose = verbose)
  adjacency <- HPOExplorer::adjacency_matrix(terms = unique(phenos$HPO_ID),
                                             hpo = hpo,
                                             verbose = verbose)
  if(!"description" %in% names(phenos)){
    phenos$description <- HPOExplorer::get_term_definition(
      ontologyId = phenos$HPO_ID)
  }
  if(!"hover" %in% names(phenos)){
    phenos <- HPOExplorer::make_hoverboxes(phenos = phenos,
                                           columns = columns,
                                           interactive = interactive,
                                           verbose = verbose)
  }
  phenoNet <- HPOExplorer::make_network_object(phenos = phenos,
                                               hpo = hpo,
                                               adjacency = adjacency,
                                               colour_var = colour_var,
                                               verbose = verbose)
  network_plot <- HPOExplorer::ggnetwork_plot(phenoNet = phenoNet,
                                              colour_var = colour_var,
                                              interactive = interactive,
                                              verbose = verbose)
  return(list(plot=network_plot,
              phenos=phenos,
              phenoNet=phenoNet,
              adjacency=adjacency
              ))
}
