#' Report plot
#'
#' Plot the results of a filtering report generated by
#' \link[MultiEWCE]{prioritise_targets}.
#' @param rep_dt Report table.
#' @param annot HPO annotations.
#' @param show_plot Show the plot.
#' @param save_plot Path to save the plot to.
#' @inheritParams ggnetwork_plot_full
#' @inheritDotParams ggplot2::ggsave
#' @returns ggplot object
#'
#' @export
#' @importFrom data.table setnafill melt
#' @importFrom methods show
#' @importFrom HPOExplorer load_phenotype_to_genes
#' @examples
#' results <- load_example_results()
#' res <- prioritise_targets(results=results)
#' gp <- report_plot(rep_dt=res$report, results=results)
report_plot <- function(rep_dt,
                        results,
                        phenotype_to_genes =
                          HPOExplorer::load_phenotype_to_genes(),
                        annot =
                          HPOExplorer::load_phenotype_to_genes(
                            "phenotype.hpoa"),
                        show_plot=TRUE,
                        save_plot=tempfile(fileext = "_report_plot.pdf"),
                        verbose=TRUE,
                        ...){

  # rep_dt <- res$report
  # results <- load_example_results()

  requireNamespace("ggplot2")
  variable <- value <- step <- NULL;

  messager("report_plot:: Preparing data.",v=verbose)
  #### Fill missing values ####
  total_diseases <- length(unique(annot[HPO_ID %in% results$HPO_ID,]$DiseaseName))
  total_genes <- length(unique(phenotype_to_genes$Gene))
  rep_dt[step=="start",]$diseases <- total_diseases
  rep_dt[step=="start",]$genes <- total_genes
  data.table::setnafill(rep_dt, type = "locf",cols = seq(2,ncol(rep_dt)))
  #### Make plot data ####
  dt <- data.table::melt(rep_dt, id.vars="step")
  dt$step <- factor(dt$step,
                        levels = unique(dt$step), ordered = TRUE)
  #### Plot ####
  messager("report_plot:: Preparing plot.",v=verbose)
  gp <- ggplot2::ggplot(dt, ggplot2::aes(x=step,
                                   y=value,
                                   fill=variable,
                                   label=value)) +
    ggplot2::geom_bar(stat = "identity",
                      alpha=.8,
                      show.legend = FALSE) +
    ggplot2::facet_grid(facets = "variable~.",
                        scales = "free") +
    ggplot2::geom_label(fill="black",
                        color="white",alpha=.8,
                        vjust = 0) +
    ggplot2::scale_fill_viridis_d() +
    ggplot2::scale_y_continuous(expand=ggplot2::expansion(mult = c(0,.2))) +
    ggplot2::theme_bw() +
    ggplot2::labs(y="Counts") +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1),
                   strip.background = ggplot2::element_rect(fill = "transparent"))

  if(isTRUE(show_plot)) methods::show(gp)
  if(!is.null(save_plot)){
    messager("Saving plot ==>",save_plot,v=verbose)
    dir.create(dirname(save_plot), showWarnings = FALSE, recursive = TRUE)
    ggplot2::ggsave(filename = save_plot,
                    plot = gp,
                    ...)
  }
  return(gp)
}
