#' Summary plot
#'
#' Generate a plot summarising the cell type-phenotype enrichment
#' results generated by \link[MultiEWCE]{gen_results}.
#' @param count_var Variable to get counts for per \code{group_var}.
#' @param group_var Variable to group counts by.
#' @param keywords Keywords supplied to search for phenotypes.
#'  Will be used to generate the plot title..
#' @inheritParams ggnetwork_plot_full
#' @inheritParams HPOExplorer::subset_descendants
#' @inheritParams HPOExplorer::ggnetwork_plot
#' @inheritParams ggplot2::scale_fill_viridis_c
#' @returns ggplot or plotly object
#'
#' @export
#' @import ggplot2
#' @importFrom plotly ggplotly
#' @importFrom scales pretty_breaks
#' @examples
#' #' ancestor <- "Neurodevelopmental delay"
#' plt_pheno_count <- summary_plot(count_var = "Phenotype",
#'                                 group_var = "CellType",
#'                                 ancestor = ancestor)
#' plt_cell_count <- summary_plot(count_var = "CellType",
#'                                 group_var = "Phenotype",
#'                                 ancestor = ancestor)
summary_plot <- function(results = load_example_results(),
                         count_var = "Phenotype",
                         group_var = "CellType",
                         keywords = NULL,
                         q_threshold = 0.0005,
                         fold_threshold = 1,
                         cell_type = NULL,
                         ancestor = NULL,
                         hpo = HPOExplorer::get_hpo(),
                         phenotype_to_genes =
                           HPOExplorer::load_phenotype_to_genes(),
                         option = "magma",
                         interactive = TRUE,
                         verbose = TRUE){
  # templateR:::source_all()
  # templateR:::args2vars(summary_plot)

  requireNamespace("ggplot2")

  #### Subset results ####
  phenos <- subset_phenos(phenotype_to_genes = phenotype_to_genes,
                          ancestor = ancestor,
                          results = results,
                          hpo = hpo,
                          cell_type = cell_type,
                          q_threshold = q_threshold,
                          fold_threshold = fold_threshold,
                          verbose = verbose)

  #### Aggregate counts ####
  counts_df <- agg_results(phenos = phenos,
                           count_var = count_var,
                           group_var = group_var)
  #### Make subtitle ####
  ## plotly doesn't inherit subtitle arg from ggplot,
  ## so need to append it to the title.
  subtitle <-  paste0(
    if(!is.null(keywords)){shQuote(paste(keywords,collapse = ", "))},
    " (",formatC(length(unique(phenos$Phenotype)),big.mark = ","),
    " ",tolower(count_var),"s)")
  #### Make plot ####
  plt <- ggplot(counts_df,
                aes_string(x = group_var,
                           y = "count",
                           fill = "mean_fold_change",
                           mean_q = "mean_q",
                           mean_sd_from_mean = "mean_sd_from_mean",
                           values = "values")) +
    geom_col() +
    labs(title = paste0("Enrichment results associated with:\n",
                        subtitle
    ),
    x = group_var,
    y = paste(count_var,"count"),
    fill = "Mean fold change") +
    scale_y_continuous(breaks = scales::pretty_breaks(),
                       expand = expansion(mult = c(0, .1))) +
    scale_fill_viridis_c(option = option) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45,
                                     vjust = 0.5, hjust = 1,
                                     size = 10))
  if(isTRUE(interactive)){
    plotly::ggplotly(plt) |>
      plotly::layout(hoverlabel = list(align = "left"),
                     margin = list(l = 0, r = 0,
                                   b = 0, t = 70,
                                   pad = 0) )
  } else {
    return(plt)
  }
}
