#' Gene therapy targets
#'
#' Identify the overlap between your prioritised list of gene therapy targets
#' and currently existing gene therapy targets that are currently on the market
#' or are in clinical trials. Uses data from the
#' \href{https://db.idrblab.net/ttd/full-data-download}{
#' Therapuetic Target Database}.
#' @param top_targets Top targets generated by
#'  \link[MultiEWCE]{prioritise_targets}.
#' @param drug_types Filter results by drug type.
#' @param highest_status Filter results by drug approval status.
#' @param show_plot Show the plot.
#' @inheritParams load_example_ctd
#'
#' @export
#' @importFrom utils tail
#' @examples
#' top_targets <- MultiEWCE::example_targets$top_targets
#' top_targets <- HPOExplorer::add_genes(top_targets[q<0.05])
#' res <- ttd_check(top_targets=top_targets)
ttd_check <- function(top_targets,
                      save_dir = tools::R_user_dir(package = "MultiEWCE",
                                                   which = "cache"),
                      drug_types = NULL,
                      highest_status = NULL,
                      show_plot = TRUE){
  # top_targets <- prioritise_targets(
  #   keep_deaths = NULL,
  #   keep_tiers = NULL,
  #   severity_threshold_max = NULL,
  #   severity_threshold = NULL,
  #   pheno_frequency_threshold = NULL,
  #   keep_onsets = NULL,
  #   keep_ont_levels = seq(4),
  #   keep_celltypes = NULL,
  #   top_n = 2,
  #   group_vars = c("hpo_id","disease_id"))$top_targets
  # drug_types <- c("Gene therapy"
    # "Antisense drug",
    # "Antisense oligonucleotide",
    # "Aptamer",
    # "Combination drug (Antisense drug)",
    # "CAR T Cell Therapy",
    # "CAR T Cell Therapy (Dual specific)",
    # "CAR-NK Cell therapy",
    # "CAR-NKT Cell therapy",
    # "CAR-PBMC Cell therapy",
    # "mRNA therapy",
    # "RNAi therapeutics",
    # "Short hairpin RNA",
    # "siRNA drug",
    # "Small activating RNA",
    # "Small interfering RNA",
    # "TCR-T cell therapy",
    # "Peptide",
    # "Protein",
    # "Protein/peptide",
    # "Protein/peptide drug"
  # )

  TARGETID <- DRUGNAME <- DRUGTYPE <- DRUGID <-
    GENENAME2 <- prioritised <- HIGHEST_STATUS <- NULL;

  ttdi <- ttd_import(save_dir = save_dir)
  #### Filter results to only gene therapies #####
  dat_sub <- ttdi$merged[!is.na(TARGETID) &
                         !is.na(GENENAME2) &
                         GENENAME2!="",]
  #### Filter by drug type ####
  if(!is.null(drug_types)){
    dat_sub <- dat_sub[
      grepl(paste(drug_types,collapse = "|"),DRUGNAME,ignore.case = TRUE) |
      grepl(paste(drug_types,collapse = "|"),DRUGTYPE,ignore.case = TRUE),]
  }
  #### Filter by status ####
  if(!is.null(highest_status)){
    dat_sub <- dat_sub[HIGHEST_STATUS %in% highest_status,]
  }
  #### Filter to only those in top_targets ####
  dat_sub2 <- (merge(
        dat_sub,
        top_targets,
        by.x = "GENENAME3",
        by.y = "gene_symbol")[,c("GENENAME2","TARGETID","TARGNAME",
                                 "INDICATI","DRUGID","DRUGNAME",
                                 "HIGHEST_STATUS",
                                 "disease_name","disease_id","hpo_name",
                                 "CellType","ontLvl")] |>
    unique())
  #### Count proportion of drugs that our analyses captured ####
  length(unique(dat_sub2$DRUGID)) / length(unique(dat_sub$DRUGID))
  length(unique(paste0(dat_sub2$DRUGID,dat_sub2$INDICATI,dat_sub2$GENENAME2)))
  dat_sub[,prioritised:=(DRUGID %in% dat_sub2$DRUGID)]
  #### Plot ####
  plt <- ttd_plot(dat_sub = dat_sub)
  if(isTRUE(show_plot)){
    methods::show(plt)
  }
  return(
    list(data=dat_sub,
         data_overlap=dat_sub2,
         plot=plot)
  )
}
